lang: en
title: Kansas City Donuts
tagline: Reviewing the Best Donuts in Kansas City
email: kcdonutsbest@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My qualifications as a Kansas City donut critic: I love to eat 
  donuts and I've lived in the KC metro area my whole life. This 
  site chronicles my journey to find the best donuts in Kansas
  City, one review at a time.
baseurl: ""
url: "https://kcdonuts.best"
permalink: pretty
#favicon: /path/to/favicon.png
#gh_sponsor: 
#hide_share_buttons: true
theme_color: "#673ab7"
#fixed_navbar: top

paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname:

remote_theme: chrisrhymes/bulma-clean-theme@v0.11.2
theme: bulma-clean-theme
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

# defaults:
#   -
#     scope:
#       path: ""
#       type: "pages"
#     values:
#       show_sidebar: true
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       author: "C.S. Rhymes"
#       layout: post
#       image: https://via.placeholder.com/1200x800
#       show_sidebar: true

markdown: kramdown
highlighter: rouge

# footer_menu: example_footer_menu

# collections:
#   products: 
#     output: true
#     layout: product
#     image: https://via.placeholder.com/800x600
#     show_sidebar: false